

image: node:10.15.3

# Workflow Configuration

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          caches:
            - node
          script:
            - npm install
#            - npm test
#      - step:
#          name: Lint the node package
#          script:
#            # Run your linter of choice here
#            - npm install
#            - npm run lint
#          caches:
#            - node
  branches:
    develop:
      - step:
          name: Build, Test and deploy
          caches:
            - node
          script:
            - npm install
  #              - npm test
            - npm run build
            - npm run generate
            - pipe: atlassian/firebase-deploy:1.0.0
              variables:
                API_KEY: $API_KEY
                AUTH_DOMAIN: $AUTH_DOMAIN
                DATABASE_URL: $DATABASE_URL
                FIREBASE_TOKEN: $FIREBASE_TOKEN_CI
                PROJECT_ID: $PROJECT_ID
                STORAGE_BUCKET: $STORAGE_BUCKET
                MESSAGING_SENDER_ID: $MESSAGING_SENDER_ID
                APP_ID: $APP_ID
                MEASUREMENT_ID: $MEASUREMENT_ID
                EXTRA_ARGS: '--only hosting,functions'
#       - step:
#           name: Deploy to Production
#           deployment: Production
# #          trigger: manual
#           clone:
#             enabled: false
#           caches:
#               - node
#           script:
#             - pipe: atlassian/firebase-deploy:1.0.0
#               variables:
#                 FIREBASE_TOKEN: $FIREBASE_TOKEN_CI
#                 PROJECT_ID: 'z-bets'
#                 EXTRA_ARGS: '--only hosting'